name: Publish VPAT
description: Publish a VPAT to the docs site
author: Deque Systems, Inc.

inputs:
  docs-site-base-branch:
    description: The base branch of the docs-site repository
    default: main
  docs-site-github-token:
    description: GitHub token to access the docs-site repository
    required: true
  docs-site-repository:
    description: GitHub repository containing the docs-site
    required: true
  docs-site-vpat-directory:
    description: Directory where the VPAT should be published in the docs-site repository
    default: static/vpats
  product-id:
    description: Brief token that identifies your product - should match product id in docs site
    required: true
  vpat-content:
    description: The VPAT content to publish as a string of HTML without escape characters
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
