name: Test

on:
  - workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      # For testing purposes, publish to this repository
      TARGET_REPO_NAME: dequelabs/action-vpat-publish
    steps:
      - uses: actions/checkout@v3

      - name: Read VPAT content
        id: read_content
        run: |
          content=$(cat test/vpat.html)
          echo "::set-output name=content::$content"

      - name: Test publish action
        uses: ./
        with:
          target-repo: ${{ env.TARGET_REPO_NAME }}
          target-repo-github-token: ${{ secrets.GITHUB_TOKEN }}
          target-repo-base-branch: main
          target-repo-vpat-directory: vpats
          product-id: test
          vpat-content: ${{ steps.read_content.outputs.content }}

      - name: Test publish action again to simulate updating an existing PR
        uses: ./
        with:
          target-repo: ${{ env.TARGET_REPO_NAME }}
          target-repo-github-token: ${{ secrets.GITHUB_TOKEN }}
          target-repo-base-branch: main
          target-repo-vpat-directory: vpats
          product-id: test
          vpat-content: ${{ steps.read_content.outputs.content }}
